# Generated by Django 3.2.8 on 2021-10-15 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('makanan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('makanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesanan', to='makanan.makanan')),
            ],
        ),
    ]
