# Generated by Django 3.2.8 on 2021-10-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='makanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemmakan', models.TextField(default='')),
                ('jenismakan', models.CharField(max_length=200)),
                ('jumlahmakan', models.IntegerField(max_length=10)),
                ('hargamakan', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
