# Generated by Django 3.2.8 on 2021-10-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_makanan_jumlahmakan'),
    ]

    operations = [
        migrations.CreateModel(
            name='minuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemminum', models.TextField(default='')),
                ('jenisminum', models.CharField(max_length=200)),
                ('jumlahminum', models.IntegerField()),
                ('hargaminum', models.IntegerField()),
            ],
        ),
    ]
